### ISSUE TITLE
Copied config does not work

### ISSUE THREAD

**Issue by luismanson** [budimanjojo/dotfiles#3242]
Hello, I've been trying to modularize my config using a reference and 've found yours to be tidy and functional, thanks!  

However I need a bit of help setting this from the instructions
After copy (budiman-vm) and define a new host in the flake.nix:
> `tepe-vm = myLib.mkNixosSystem "x86_64-linux" "tepe-vm" "budiman";`

I try to build it with:
` sudo nixos-rebuild  build-vm --flake .#tepe-vm`

I can not get rebuild to work using the new hosts it fails with some kind of syntax error, but cant figure where it is. building budiman-vm, works fine.

```
error:
       … while calling the 'seq' builtin

         at /nix/store/mcwr2j04fikfsrsaq76f4bviinvl6zql-source/lib/modules.nix:322:18:

          321|         options = checked options;
          322|         config = checked (removeAttrs config [ "_module" ]);
             |                  ^
          323|         _module = checked (config._module);

       … while evaluating a branch condition

         at /nix/store/mcwr2j04fikfsrsaq76f4bviinvl6zql-source/lib/modules.nix:261:9:

          260|       checkUnmatched =
          261|         if config._module.check && config._module.freeformType == null && merged.unmatchedDefns != [] then
             |         ^
          262|           let

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: getting status of '/nix/store/j3vxq5vy6ngxmhk9gl64l9w3zj7ksr6g-source/nixos/hosts/tepe-vm': No such file or directory
```
Do you have any clue where the issue is?

**Comment by budimanjojo** [comment]
Sorry for being late to reply. It seems like the error indicate that the file doesn't exist. Usually it's because you haven't do `git add` to that file

**Comment by luismanson** [comment]
Hey, no problem! Thank you for taking the time to share this and help! I really love how this is organized.  
That chezmoi config is also nice! 


Cheers!
